[eos-bash-shared] ; eos-sendlog enhancement, and some code cleanup

diff --git a/eos-connection-checker b/eos-connection-checker
--- a/eos-connection-checker
+++ b/eos-connection-checker
@@ -1,44 +1,49 @@
 #!/bin/bash
 #
 # Checks that an internet connection exists.
-# Return value is 0 on success, or another number on failure.
-#
-# Program 'curl-exit-code-to-string' can convert the error code to a human readable message (see below).
+# Return value is 0 on success, or another number on failure (see also: 'curl-exit-code-to-string').
 #
 # Example usage:
 #    eos-connection-checker && echo connection is ON
 #    eos-connection-checker || echo connection is OFF
 #    eos-connection-checker || curl-exit-code-to-string $?
 
-GetFastestMirror() {
-    # This assumes eos-rankmirrors has been executed on the current list.
-    # If not, then this does essentially nothing.
-    grep -A10 "^# mirror [ ]*update-level" /etc/pacman.d/endeavouros-mirrorlist | grep "^# https://" | sort -k4 | head -n1 | awk '{print $2}' | sed 's|\([^$]*\)/\$.*|\1|'
+FastestMirror() { grep -m1 "^# https://" $ml | sed 's|# \([^$]*\)/\$.*|\1|' ; }                           # assumes the list was created with eos-rankmirrors
+AllMirrors()    { grep "^Server[ ]*=[ ]*https://" $ml | sed 's|^Server[ ]*=[ ]*\([^$]*\)/\$.*|\1|' ; }
+
+Test() {
+    local url="$1"
+    /usr/bin/curl --silent --fail --connect-timeout 8 "$url" >/dev/null
+    retval=$?
+    if [ $retval -eq 0 ] ; then
+        [ "$verbose" = "yes" ] && echo "Mirror = $url" >&2
+        exit 0                     # connection exists
+    fi
 }
 
 Main() {
-    # These addresses will be used for checking the availability of internet access.
-    # If you have issues with the addresses, please report this at this site:
-    #     https://forum.endeavouros.com
-    #
-    local URLs=(
-        # This should work globally.
-        #https://geoip.kde.org/v1/calamares   # this doesn't seem to work anymore?
-
-        # EndeavourOS mirrors (fastest first).
-
-        $(GetFastestMirror)
-        $(grep ^Server /etc/pacman.d/endeavouros-mirrorlist | sed 's|^Server[ ]*=[ ]*\([^$]*\)/\$.*|\1|')
-    )
+    local -r ml=/etc/pacman.d/endeavouros-mirrorlist
+    local -r fastest="$(FastestMirror)"
+    local others=""
     local URL
     local retval
+    local verbose=no
 
-    for URL in "${URLs[@]}" ; do
-        /usr/bin/curl --silent --fail --connect-timeout 8 "$URL" >/dev/null
-        retval=$?
-        [ $retval -eq 0 ] && break
+    case "$1" in
+        -v | --verbose) verbose=yes ;;   # will show the responding mirror URL
+    esac
+
+    if [ "$fastest" ] ; then
+        Test "$fastest"
+        others="$(AllMirrors | grep -v "$fastest")"
+    else
+        others="$(AllMirrors)"
+    fi
+
+    for URL in $others ; do
+        Test "$URL"
     done
-    return $retval
+    return $retval                       # no connection
 }
 
 Main "$@"
diff --git a/eos-sendlog b/eos-sendlog
--- a/eos-sendlog
+++ b/eos-sendlog
@@ -1,19 +1,72 @@
 #!/bin/bash
 
-# Like the "old" eos-sendlog, but can also take the command as parameter.
-# The command from parameters will output in English.
-#
-# Tip: multiple commands (including parameters) can be given too:
-#    eos-sendlog bash -c "command1 ; command2 ; command3"
-#
-# Tip2: user can select the pastebin provider (see 'eos-sendlog-helper -h'):
-#    echo foobar | eos-sendlog --termbin
+# Like the "old" eos-sendlog, with an addition to take the input from multiple commands.
+
+DIE()     { echo "$progname: error: $1" >&2; exit 1; }
+Verbose() { [ $verbose = yes ] && echo -e "$@" >&2 ; }
+
+Options() {
+    local opts
+    local sopts="hv"
+    local lopts="0x0,dpaste,termbin"    # pastebin options
+    lopts+=",help,verbose"              # general options
+
+    opts="$(/bin/getopt -o="$sopts" --longoptions "$lopts" --name "$progname" -- "$@")" || Usage 1
+    eval set -- "$opts"
+
+    while true ; do
+        case "$1" in
+            --0x0 | --dpaste | --termbin)  pastebin_service="$1" ;;
+            -h | --help)                   Usage 0 ;;
+            -v | --verbose)                verbose=yes ;;
+            --)                            shift; break ;;
+            *)                             break ;;
+        esac
+        shift
+    done
+    [ "$1" ] && commands="$*"
+}
+
+Usage() {
+    cat <<EOF >&2
+Usage:
+    1. input from one command via stdin:
+          <command> | $progname [$progname-options]
+    2. input from outputs of multiple commands:
+          $progname [$progname-options] "<command1> ; <command2> ; <command3> ..."
+${progname}-options:
+    --0x0           Use only pastebin 0x0.st.
+    --dpaste        Use only pastebin dpaste.com.
+    --termbin       Use only pastebin termbin.com.
+    --help, -h      This help.
+    --verbose, -v   Be more verbose.
+Without ${progname}-options the services are tried in order:
+    1. 0x0
+    2. dpaste
+    3. termbin
+until one succeeds or all fail.
+
+Examples:
+    inxi -Fza | $progname --dpaste
+    $progname "pacman -Qm ; lsusb"
+EOF
+    [ "$1" ] && exit "$1"
+}
 
 Main() {
-    if [ "$1" ] ; then
-        LANG=C "$@" | eos-sendlog-helper
+    local progname=${0##*/}
+    local pastebin_service=""
+    local commands=""
+    local verbose=no
+
+    Options "$@"
+
+    if [ "$commands" ] ; then
+        Verbose "==> input from commands..."
+        LANG=C bash -c "$commands" | eos-sendlog-helper $pastebin_service
     else
-        eos-sendlog-helper "$@"    # $@ = options for eos-sendlog-helper
+        Verbose "==> input from stdin..."
+        eos-sendlog-helper $pastebin_service
     fi
 }
 
