[eos-bash-shared] eos-update: added option --reset-pacmanconf

diff --git a/eos-update b/eos-update
--- a/eos-update
+++ b/eos-update
@@ -143,7 +143,7 @@ EditMirrorlist() {
             linenr=""
         fi
     fi
-    RunInTerminal "echo 'Starting to edit $list:'; sudo $editor $linenr $list"
+    RunInTerminal "echo '==> Editing $list with $editor:'; sudo $editor $linenr $list"
 }
 
 ResetKeyrings() {
@@ -188,7 +188,7 @@ CheckReposPacmanConf() {
         extra
     )
     local toberemoved=() tobeadded=()
-    local -r file=/etc/pacman.conf
+    local -r file=$pacmanconf
     local stop=no
 
     for item in "${problem_repos[@]}" ; do
@@ -223,30 +223,25 @@ FaillockCheck() {
     fi
 }
 
-OptionCheck() {
-    case "$1" in
-        --nvidia) IsSupportedOS "$1" || return 1 ;;
-    esac
-    return 0
+ResetPacmanConf() {
+    local -r pacmanconf_url="https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/refs/heads/main/airootfs/etc/pacman.conf"
+    local -r tmpfile=$(mktemp)
+    wget -qO $tmpfile "$pacmanconf_url" || DIE "cannot fetch $pacmanconf_url"
+    local -r time=$(date +%Y%m%d-%H%M%S)
+    sudo mkdir -p /etc/.EOS_BACKUPDIR
+    sudo mv $pacmanconf /etc/.EOS_BACKUPDIR/${pacmanconf##*/}.$time
+    sudo gzip "/etc/.EOS_BACKUPDIR/${pacmanconf##*/}.$time"
+    sudo cp $tmpfile $pacmanconf
+    rm -f $tmpfile
 }
 
-Options() {
-    local opts
-    local lopts="aur,clear-databases,descriptions,dump-options,fast,keyrings-reset,nvidia,no-keyring,no-sync,helper:"
-    lopts+=",min-free-bytes:,pacdiff,paru,yay,pacman,help,run-mode:,faillock-check"
-    lopts+=",show-only-fixed,show-upstream-news,check-mirrors-arch,check-mirrors-eos,check-mirrors,edit-mirrorlist:"
-    lopts+=",check-databases"
-    local sopts="dh"
-
-    opts="$(LANG=C /usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || {
-        echo2 "==> more info with command: $progname --help"
-        exit 1
-    }
-    eval set -- "$opts"
-
+SingleOptions() {
     local ret=0
-    while true ; do
+    while [ "$1" ] ; do
         case "$1" in
+            --reset-pacmanconf)                  ResetPacmanConf
+                                                 exit 0
+                                                 ;;
             --check-mirrors)                     CheckYourEndeavourosMirrorlist || ((ret++))
                                                  CheckYourArchMirrorlist        || ((ret++))
                                                  exit $ret
@@ -257,9 +252,48 @@ Options() {
             --check-mirrors-eos)                 CheckYourEndeavourosMirrorlist || ((ret++))
                                                  exit $ret
                                                  ;;
-            --edit-mirrorlist)                   EditMirrorlist "$2"; exit 0 ;;
+            --edit-mirrorlist)                   EditMirrorlist "$2"
+                                                 exit 0
+                                                 ;;
+            --show-only-fixed)                   which arch-audit >/dev/null && arch-audit -u
+                                                 exit
+                                                 ;;
+            --show-upstream-news)                local br=$(eos_select_browser)
+                                                 [ "$br" ] && $br https://archlinux.org/news
+                                                 exit
+                                                 ;;
+            --dump-options)                      lopts="${lopts//:/}"
+                                                 lopts="--${lopts//,/ --}"
+                                                 sopts="${sopts//:/}"
+                                                 sopts="$(echo "$sopts" | sed -E 's|([a-z])| -\1|g')"
+                                                 echo $lopts $sopts
+                                                 exit 0
+                                                 ;;
+            -h | --help)                         Usage
+                                                 exit 0
+                                                 ;;
+        esac
+        shift
+    done
+}
+
+Options() {
+    local opts
+
+    opts="$(LANG=C /usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || {
+        echo2 "==> more info with command: $progname --help"
+        exit 1
+    }
+    eval set -- "$opts"
+
+    local ret=0
+    while true ; do
+        case "$1" in
+            --reset-pacmanconf | --check-mirrors | --check-mirrors-arch | --check-mirrors-eos | --edit-mirrorlist | --show-only-fixed | --show-upstream-news | --dump-options | -h | --help)
+                : # already handled in SingleOptions
+                ;;
             --fast)                              eufast=yes ;;
-            --nvidia)                            OptionCheck "$1" && nvidia=yes ;;
+            --nvidia)                            nvidia=yes ;;
             --no-keyring)                        keyring=no ;;
             --descriptions | -d)                 descriptions=yes ;;
             --faillock-check)                    faillockcheck=yes ;;
@@ -273,25 +307,6 @@ Options() {
             --aur)                               SetHelper; eufast_opt+=" $1" ;;
             --paru | --yay | --pacman)           SetHelper "${1/--/}" ;;
 	    --pacdiff)                           pacdiffer="$pacdiffer_cmd_default" ;;
-            --show-only-fixed)
-                which arch-audit >/dev/null && arch-audit -u
-                exit
-                ;;
-            --show-upstream-news)
-                local br=$(eos_select_browser)
-                [ "$br" ] && $br https://archlinux.org/news
-                exit
-                ;;
-            --dump-options)
-                lopts="${lopts//:/}"
-                lopts="--${lopts//,/ --}"
-                sopts="${sopts//:/}"
-                sopts="$(echo "$sopts" | sed -E 's|([a-z])| -\1|g')"
-                echo $lopts $sopts
-                exit 0
-                ;;
-
-            -h | --help) Usage; exit 0 ;;
             
             --) shift ; break ;;
         esac
@@ -329,6 +344,8 @@ Options:
   --check-mirrors-eos     Check file $eml for unsupported mirrors.
   --check-mirrors-arch    Check file $aml for unsupported mirrors.
   --edit-mirrorlist <val> Edit chosen mirrorlist file. Supported values: arch, endeavouros. No default.
+  --reset-pacmanconf      Replace your current $pacmanconf with the EndeavourOS original.
+                          Note: do this only if you need to restore the original file.
   --fast                  Do a *fast check* for updates in order to reduce the amount of network traffic.
                           Note that the fast check
                             * applies to only updates on EndeavourOS and Arch repos, and optionally on AUR
@@ -373,15 +390,6 @@ Tip: create an alias in file ~/.bashrc for $progname to have the options you nee
 EOF
 }
 
-IsSupportedOS() {
-    if [ -x /usr/bin/eos-kernel-nvidia-update-check ] ; then
-        return 0
-    else
-        WARN "the Nvidia check requires package 'eos-bash-shared' fully installed, option $1 ignored."
-        return 1
-    fi
-}
-
 DiskSpace() {
     local available=$(findmnt / -nbo avail)
     local min=$min_free_bytes
@@ -418,17 +426,31 @@ Main() {
     local -r MAGENTA=$'\e[0;95m'
     local -r RESET=$'\e[0m'
 
-    CheckReposPacmanConf
+    local -r pacmanconf=/etc/pacman.conf
+    local -r eml=/etc/pacman.d/endeavouros-mirrorlist
+    local -r aml=/etc/pacman.d/mirrorlist
+
+    local min_free_bytes=$((1000 * 1000 * 1000))  # default: 1 GB
+
+    local lopts="aur,clear-databases,descriptions,dump-options,fast,keyrings-reset,nvidia,no-keyring,no-sync,helper:"
+    lopts+=",min-free-bytes:,pacdiff,paru,yay,pacman,help,run-mode:,faillock-check"
+    lopts+=",show-only-fixed,show-upstream-news,check-mirrors-arch,check-mirrors-eos,check-mirrors,edit-mirrorlist:"
+    lopts+=",check-databases,reset-pacmanconf"
+    local sopts="dh"
 
     trap Cleanup EXIT
 
     source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1
+
+    SingleOptions "$@"
+
+    CheckReposPacmanConf
+
     source /usr/share/endeavouros/scripts/translations.bash || exit 1
 
     _init_translations
     
     local helper="pacman"
-    local min_free_bytes=$((1000 * 1000 * 1000))  # default: 1 GB
 
     local lock=/var/lib/pacman/db.lck
     local rmopt=f
@@ -445,8 +467,6 @@ Main() {
     local sync="sync"
     local eufast=no
     local eufast_opt="--arch --endeavouros"
-    local -r eml=/etc/pacman.d/endeavouros-mirrorlist
-    local -r aml=/etc/pacman.d/mirrorlist
 
     Options "$@"
 
