[eos-bash-shared] added function CanRunYad to eos-script-lib-yad and used it in eos-pacdiff

diff --git a/eos-script-lib-yad b/eos-script-lib-yad
--- a/eos-script-lib-yad
+++ b/eos-script-lib-yad
@@ -41,6 +41,12 @@ source $translations_dir/translations.bash || {
     exit 1
 }
 
+CanRunYad() {
+    [ -x /bin/yad ]                   || return 1    # fail, yad not installed
+    [ -d /usr/include/webkitgtk-4.1 ] || return 2    # fail, webkit2gtk-4.1 not installed
+    return 0                                         # OK
+}
+
 yad_missing_check() {
     if [ "${EOS_YAD_MISSING_NOTIFICATION^^}" = "YES" ] ; then
         if ! which yad &>/dev/null ; then
